# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertweet',
            old_name='follower',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='usertweet',
            old_name='follwer_id',
            new_name='tweet_msg',
        ),
    ]
